# Generated by Django 5.1.7 on 2025-05-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0002_hypertensionpredictionlog'),
        ('userManagement', '0005_user_usergender_user_userheight_user_userweight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetespredictionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.user'),
        ),
        migrations.AlterField(
            model_name='hypertensionpredictionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.user'),
        ),
    ]
