# Generated by Django 5.1.7 on 2025-05-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurition_tracker', '0002_foodlog_category'),
        ('userManagement', '0005_user_usergender_user_userheight_user_userweight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to='userManagement.user'),
        ),
    ]
